### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by arzzen** [arzzen/all-exit-error-codes#18]

**Comment by BhaveshSGupta** [comment]
I can take this one, Links need to be updated anything else?

**Comment by yasirunilan** [comment]
can I work on this

**Comment by arzzen** [comment]
@BhaveshSGupta just update links and improve description

**Comment by michelvosje** [comment]
Creating pull-request in a minute. Not sure how this works...

**Comment by michelvosje** [comment]
Am i done now for 1/4 of my t-shirt?

Btw can i do more tickets on your repo? Or does it need to be from different repo's?

**Comment by BhaveshSGupta** [comment]
@michelvosje Actually when some has said that he is solving the issue, then you should first confirm with the issuer and the one who is solving the issue before creating the Pull Request, because this way two people don't waste their time in solving same issue. This is general practice in all Open Source Projects.

**Comment by michelvosje** [comment]
They didn't say they were actually going to work on it.  Neither did I when I started... Their reaction was +13 hours before I started. So I assumed nobody picked it up. 

For the others. Sry if you guys did hard work now.

**Comment by michelvosje** [comment]
BTW I have seen dozens of repos where people state they would work on an issue. 6 days later no response no Pull Request.
